version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "partygames-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-jhlo0fua5gk0"
s3_prefix = "partygames-app"
region = "ap-southeast-2"
capabilities = "CAPABILITY_IAM"
