AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  partygames-app

  Serverless REST api for party games 
  
Globals:
  Function:
    Timeout: 2

Resources:
  RestApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: Party Games Api Gateway
      StageName: prod
      Models:
        Game: 
          type: object
          required:
            - type
            - allowNicknames
          properties:
            type:
              type: string
            allowNicknames:
              type: boolean
            maxPartitions:
              type: integer
            name:
              type: string

  GameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/game
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Games
      Environment:
        Variables:
          GAMES_TABLE_NAME: Games
      Events:
        GetGameApi:
          Type: Api
          Properties:
            RestApiId: { Ref: 'RestApiGateway' }
            Path: /games/{id}
            Method: get
        CreateGameApi:
          Type: Api
          Properties:
            RestApiId: { Ref: 'RestApiGateway' }
            Path: /games
            Method: post
            RequestModel:
              Model: Game
              Required: true

  gamesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Games
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Game function"
    Value: !Sub "https://${RestApiGateway}.execute-api.${AWS::Region}.amazonaws.com/prod/games/"
