AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  partygames-app

  Serverless REST api for party games 
  
Globals:
  Function:
    Timeout: 3

Resources:
  GameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/game
      Handler: app.lambdaHandler
      Runtime: nodejs14.x
      Events:
        getGame:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /game
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  GameApi:
    Description: "API Gateway endpoint URL for Prod stage for Game function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/game/"
  GameFunction:
    Description: "Game Lambda Function ARN"
    Value: !GetAtt GameFunction.Arn
  GameFunctionIamRole:
    Description: "Implicit IAM Role created for Game function"
    Value: !GetAtt GameFunctionRole.Arn
