AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  partygames-app

  Serverless REST api for party games 
  
Globals:
  Function:
    Timeout: 2

Resources:
  GameFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/game
      Handler: app.handler
      Runtime: nodejs14.x
      Policies:
        - DynamoDBCrudPolicy:
            TableName: Games
      Environment:
        Variables:
          GAMES_TABLE_NAME: Games
      Events:
        getGame:
          Type: Api
          Properties:
            Path: /games/{id}
            Method: get
        createGame:
          Type: Api
          Properties:
            Path: /games
            Method: post
  
  gamesTable:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: Games
      AttributeDefinitions: 
        - AttributeName: id
          AttributeType: S
      KeySchema: 
        - AttributeName: id
          KeyType: HASH
      ProvisionedThroughput: 
        ReadCapacityUnits: 1
        WriteCapacityUnits: 1
      StreamSpecification:
        StreamViewType: NEW_IMAGE

Outputs:
  Api:
    Description: "API Gateway endpoint URL for Prod stage for Game function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/game/"
